# -*- coding: utf-8 -*-
"""筛选漏斗的原因码常量。

screen_result.reason_codes 是一个 JSON list 累积所有触发的原因码。
命名约定：
- Q0/Q1/.../Q6: 质量层（PRD 第 5 节）
- R1/.../R12: 风险层（PRD 第 6 节）
- V1/.../V5: 价格层（PRD 第 7 节）
- {code}_PASS: 通过该规则
- {code}_FAIL_{reason}: 不通过 + 具体原因
- {code}_{tag}: 标签（如 STRONG_TRACK_RECORD）

中文标签由前端单独维护映射，便于 reason_codes_label.py 在 M6 实现。
"""

# ============ Q-Layer ============
Q0_EXCLUDED_BANK = "Q0_EXCLUDED_BANK"
Q0_EXCLUDED_INSURANCE = "Q0_EXCLUDED_INSURANCE"
Q0_EXCLUDED_BROKER = "Q0_EXCLUDED_BROKER"
Q0_EXCLUDED_REIT = "Q0_EXCLUDED_REIT"
Q0_EXCLUDED_ETF = "Q0_EXCLUDED_ETF"
Q0_EXCLUDED_FUND = "Q0_EXCLUDED_FUND"
Q0_EXCLUDED_SPAC = "Q0_EXCLUDED_SPAC"
Q0_EXCLUDED_ADR = "Q0_EXCLUDED_ADR"
Q0_EXCLUDED_PREFERRED = "Q0_EXCLUDED_PREFERRED"
Q0_EXCLUDED_WARRANT = "Q0_EXCLUDED_WARRANT"
Q0_EXCLUDED_SHELL = "Q0_EXCLUDED_SHELL"
Q0_EXCLUDED_OTHER = "Q0_EXCLUDED_OTHER"
Q0_EXCLUDED_FLAG = "Q0_EXCLUDED_FLAG"  # company.is_excluded=True

Q1_INSUFFICIENT_HISTORY = "Q1_INSUFFICIENT_HISTORY"  # < 5 财年

Q3_PASS = "Q3_PASS"
Q3_FAIL_MEDIAN = "Q3_FAIL_MEDIAN"  # 5Y 中位数 < 20%
Q3_FAIL_COUNT = "Q3_FAIL_COUNT"    # ≥ 20% 年数 < 4/5

Q4_STRONG_TRACK_RECORD = "Q4_STRONG_TRACK_RECORD"  # 10Y ≥ 8 年达标

Q5_NEGATIVE_CAPITAL_EMPLOYED = "Q5_NEGATIVE_CAPITAL_EMPLOYED"

Q6_LIST_DATE_TOO_RECENT = "Q6_LIST_DATE_TOO_RECENT"  # 上市未满 5 年


# instrument_type 到 Q0 reason_code 的映射
Q0_BY_INSTRUMENT_TYPE = {
    "BANK": Q0_EXCLUDED_BANK,
    "INSURANCE": Q0_EXCLUDED_INSURANCE,
    "BROKER": Q0_EXCLUDED_BROKER,
    "REIT": Q0_EXCLUDED_REIT,
    "ETF": Q0_EXCLUDED_ETF,
    "FUND": Q0_EXCLUDED_FUND,
    "SPAC": Q0_EXCLUDED_SPAC,
    "ADR": Q0_EXCLUDED_ADR,
    "PREFERRED": Q0_EXCLUDED_PREFERRED,
    "WARRANT": Q0_EXCLUDED_WARRANT,
    "SHELL": Q0_EXCLUDED_SHELL,
    "OTHER": Q0_EXCLUDED_OTHER,
}


# ============ R-Layer ============
R1_HIGH_LEVERAGE = "R1_HIGH_LEVERAGE"            # net_debt/EBIT > 4
R1_LOW_COVERAGE = "R1_LOW_COVERAGE"              # interest_coverage < 3
R1_DETERIORATING_LIQUIDITY = "R1_DETERIORATING_LIQUIDITY"  # current_ratio < 1 且 2 年恶化

R2_POOR_CFO_NI = "R2_POOR_CFO_NI"                # CFO/NI < 0.7 连续 2 年
R2_PERSISTENT_FCF_NEGATIVE = "R2_PERSISTENT_FCF_NEGATIVE"  # FCF<0 在 5 年 ≥ 3 年

R3_HIGH_DILUTION = "R3_HIGH_DILUTION"            # share_count_cagr_5y > 3%

R4_SERIAL_ACQUIRER = "R4_SERIAL_ACQUIRER"        # P1 + AI 判定

R5_AUDIT_ISSUE = "R5_AUDIT_ISSUE"                # 需 AI
R6_REGULATORY_ACTION = "R6_REGULATORY_ACTION"    # 需 AI
R7_CUSTOMER_CONCENTRATION = "R7_CUSTOMER_CONCENTRATION"  # 需 AI
R8_SUPPLIER_CONCENTRATION = "R8_SUPPLIER_CONCENTRATION"  # 需 AI
R9_TURNAROUND_TRAP = "R9_TURNAROUND_TRAP"        # 需 AI
R10_MANAGEMENT_INSTABILITY = "R10_MANAGEMENT_INSTABILITY"  # 需 AI
R11_MINORITY_UNFRIENDLY = "R11_MINORITY_UNFRIENDLY"  # 需 AI
R12_DISRUPTION = "R12_DISRUPTION"                # 需 AI

R_PASS = "R_PASS"
R_RULE_ONLY = "R_RULE_ONLY"  # AI 不可用，仅硬规则结果


# ============ V-Layer ============
V1_NEGATIVE_EPS = "V1_NEGATIVE_EPS"

V2_PASS_STRICT = "V2_PASS_STRICT"      # PE ≤ 14.9
V3_PASS_STANDARD = "V3_PASS_STANDARD"  # PE ≤ 18-22 视等级
V_TOO_EXPENSIVE = "V_TOO_EXPENSIVE"
V_NO_PRICE = "V_NO_PRICE"              # 无市场价或无估值数据
