"""create core tables

Revision ID: 9ccdcd9901f0
Revises: 
Create Date: 2026-03-24 12:46:06.512031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ccdcd9901f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('market', sa.Enum('US', 'CN_A', name='market_enum'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('industry_code', sa.String(length=50), nullable=True),
    sa.Column('industry_name', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=True, comment='SEC CIK (美股)'),
    sa.Column('stock_code', sa.String(length=20), nullable=True, comment='A股代码 (如 600519)'),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('cik')
    )
    op.create_index(op.f('ix_company_industry_code'), 'company', ['industry_code'], unique=False)
    op.create_index(op.f('ix_company_market'), 'company', ['market'], unique=False)
    op.create_table('fact',
    sa.Column('fact_id', sa.String(length=128), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('taxonomy_or_account', sa.String(length=100), nullable=False, comment='us-gaap tag 或 CN 科目'),
    sa.Column('concept', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('available_date', sa.Date(), nullable=True, comment='信息可得日期'),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index('ix_fact_company_concept_period', 'fact', ['company_id', 'concept', 'period_end'], unique=False)
    op.create_index(op.f('ix_fact_company_id'), 'fact', ['company_id'], unique=False)
    op.create_table('factor_value',
    sa.Column('factor_value_id', sa.String(length=128), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('factor_code', sa.String(length=10), nullable=False, comment='S1, R1, M1, etc.'),
    sa.Column('asof_date', sa.Date(), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=True),
    sa.Column('cleaned_value', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True, comment='归一化后 0-100 分'),
    sa.Column('normalization_bucket', sa.String(length=100), nullable=True, comment='行业×市值桶'),
    sa.Column('lineage', sa.Text(), nullable=True, comment='inputs->rules 血缘'),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('factor_value_id')
    )
    op.create_index(op.f('ix_factor_value_company_id'), 'factor_value', ['company_id'], unique=False)
    op.create_index(op.f('ix_factor_value_factor_code'), 'factor_value', ['factor_code'], unique=False)
    op.create_index('ix_fv_company_factor_date', 'factor_value', ['company_id', 'factor_code', 'asof_date'], unique=False)
    op.create_table('filing',
    sa.Column('filing_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='SEC|SSE|CNINFO|SSEINFO'),
    sa.Column('form_type', sa.String(length=30), nullable=True, comment='10-K, 10-Q, 年报, etc.'),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('available_date', sa.Date(), nullable=True, comment='信息可得日期（防前视）'),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('filing_id')
    )
    op.create_index(op.f('ix_filing_company_id'), 'filing', ['company_id'], unique=False)
    op.create_table('score_snapshot',
    sa.Column('score_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('asof_date', sa.Date(), nullable=False),
    sa.Column('model_version', sa.String(length=30), nullable=False, comment='balanced|conservative|aggressive'),
    sa.Column('survival', sa.Float(), nullable=True),
    sa.Column('replication', sa.Float(), nullable=True),
    sa.Column('adaptation', sa.Float(), nullable=True),
    sa.Column('moat', sa.Float(), nullable=True),
    sa.Column('valuation', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(length=10), nullable=True, comment='Top|Watch|Reject'),
    sa.Column('gating_flags', sa.Text(), nullable=True, comment='触发的红线标记 JSON'),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_index(op.f('ix_score_snapshot_company_id'), 'score_snapshot', ['company_id'], unique=False)
    op.create_index('ix_ss_company_date_model', 'score_snapshot', ['company_id', 'asof_date', 'model_version'], unique=False)
    op.create_table('security',
    sa.Column('security_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('security_id')
    )
    op.create_index(op.f('ix_security_company_id'), 'security', ['company_id'], unique=False)
    op.create_index(op.f('ix_security_ticker'), 'security', ['ticker'], unique=False)
    op.create_table('market_bar',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_bar_security_id'), 'market_bar', ['security_id'], unique=False)
    op.create_index('ix_mb_security_date', 'market_bar', ['security_id', 'trade_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mb_security_date', table_name='market_bar')
    op.drop_index(op.f('ix_market_bar_security_id'), table_name='market_bar')
    op.drop_table('market_bar')
    op.drop_index(op.f('ix_security_ticker'), table_name='security')
    op.drop_index(op.f('ix_security_company_id'), table_name='security')
    op.drop_table('security')
    op.drop_index('ix_ss_company_date_model', table_name='score_snapshot')
    op.drop_index(op.f('ix_score_snapshot_company_id'), table_name='score_snapshot')
    op.drop_table('score_snapshot')
    op.drop_index(op.f('ix_filing_company_id'), table_name='filing')
    op.drop_table('filing')
    op.drop_index('ix_fv_company_factor_date', table_name='factor_value')
    op.drop_index(op.f('ix_factor_value_factor_code'), table_name='factor_value')
    op.drop_index(op.f('ix_factor_value_company_id'), table_name='factor_value')
    op.drop_table('factor_value')
    op.drop_index(op.f('ix_fact_company_id'), table_name='fact')
    op.drop_index('ix_fact_company_concept_period', table_name='fact')
    op.drop_table('fact')
    op.drop_index(op.f('ix_company_market'), table_name='company')
    op.drop_index(op.f('ix_company_industry_code'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
